
[buildpack]
id = "org.cloudfoundry.ruby"
name = "Ruby Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.default_versions]]
ruby = "2.4.6"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "6649b56e83ebc5791f6ccff48fa2eec02b112b994fb82297d762364c8cbfb5cc"
source = "https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.10.tar.gz"
source_sha256 = "cd51019eb9d9c786d6cb178c37f6812d8a41d6914a1edaf0050c051c75d7c358"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.2.10-linux-x64-cflinuxfs3-6649b56e.tgz"
version = "2.2.10"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "a72dc47fb959a0e0e9691e5eb886c08c02850bc7ccdbab21a844e0c3df5fb427"
source = "https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.7.tar.gz"
source_sha256 = "35cd349cddf78e4a0640d28ec8c7e88a2ae0db51ebd8926cd232bb70db2c7d7f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.7-linux-x64-cflinuxfs3-a72dc47f.tgz"
version = "2.3.7"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "34718170ef36d00277ae166d327c0ea4debf4562cd6d79950b1c78cb02cd2c5e"
source = "https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.8.tar.gz"
source_sha256 = "b5016d61440e939045d4e22979e04708ed6c8e1c52e7edb2553cf40b73c59abf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.8-linux-x64-cflinuxfs3-34718170.tgz"
version = "2.3.8"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "a7d1badf2b68d19d90147b8671bb4aa4247772e1e6fda6764c2c37f1580c9183"
source = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.4.tar.gz"
source_sha256 = "254f1c1a79e4cc814d1e7320bc5bdd995dc57e08727d30a767664619a9c8ae5a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.4-linux-x64-cflinuxfs3-a7d1badf.tgz"
version = "2.4.4"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "bedb8b6b620b64b320dbbefe9e7906d277dcaf9e2308c44ecd6deb97e5486964"
source = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.5.tar.gz"
source_sha256 = "6737741ae6ffa61174c8a3dcdd8ba92bc38827827ab1d7ea1ec78bc3cefc5198"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.5-linux-x64-cflinuxfs3-bedb8b6b.tgz"
version = "2.4.5"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "d275cd81cc8fc2663b3fae42058cf03e1599028f42ff7e3d3291ec4d07b4f1e5"
source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz"
source_sha256 = "dac81822325b79c3ba9532b048c2123357d3310b2b40024202f360251d9829b1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.1-linux-x64-cflinuxfs3-d275cd81.tgz"
version = "2.5.1"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "5d5a8f8cdfe44d9136dc7098771b32054c8dd8cd048638c4997e24e19d2675e0"
source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.gz"
source_sha256 = "9828d03852c37c20fa333a0264f2490f07338576734d910ee3fd538c9520846c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.3-linux-x64-cflinuxfs3-5d5a8f8c.tgz"
version = "2.5.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
