api = "0.2"

[buildpack]
  id = "org.cloudfoundry.ruby"
  name = "Ruby Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "2.7.*"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "1edf7db5c8642aae54f00a6428e8246ccdb1d6a160ae5d328a800a1ef47b858c"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.6.tar.gz"
    source_sha256 = "1d7ed06c673020cd12a737ed686470552e8e99d72b82cd3c26daa3115c36bea7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.6-linux-x64-cflinuxfs3-1edf7db5.tgz"
    version = "2.5.6"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "01b7d7a8a3031f15079e0ca1245e002575f47c8943f68508d86ba4f46ac24190"
    source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.7.tar.gz"
    source_sha256 = "0b2d0d5e3451b6ab454f81b1bfca007407c0548dea403f1eba2e429da4add6d4"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.7-linux-x64-cflinuxfs3-01b7d7a8.tgz"
    version = "2.5.7"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "07b3393d88022466bb38794be7e8d4c67131c30ebfc29306df59d084322a861d"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.4.tar.gz"
    source_sha256 = "4fc1d8ba75505b3797020a6ffc85a8bcff6adc4dabae343b6572bf281ee17937"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.4-linux-x64-cflinuxfs3-07b3393d.tgz"
    version = "2.6.4"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "a23c26ec93e34ca05328390107ff40034b5103afb91194ebf70f66f0c0866db4"
    source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.gz"
    source_sha256 = "66976b716ecc1fd34f9b7c3c2b07bbd37631815377a2e3e85a5b194cfdcbed7d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.5-linux-x64-cflinuxfs3-a23c26ec.tgz"
    version = "2.6.5"

  [[metadata.dependencies]]
    id = "ruby"
    name = "Ruby"
    sha256 = "68cd2baeb33c1f10a873aab8e492d4547f3b13d1a6302930ac25bcedf45d51ce"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.0.tar.gz"
    source_sha256 = "8c99aa93b5e2f1bc8437d1bbbefd27b13e7694025331f77245d0c068ef1f8cbe"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.7.0-linux-x64-cflinuxfs3-68cd2bae.tgz"
    version = "2.7.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-01T00:00:00Z
    link = "https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/"
    name = "ruby"
    version_line = "2.7.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
