
[buildpack]
id = "org.cloudfoundry.ruby"
name = "Ruby Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.default_versions]]
ruby = "2.4.6"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "6649b56e83ebc5791f6ccff48fa2eec02b112b994fb82297d762364c8cbfb5cc"
source = "https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.10.tar.gz"
source_sha256 = "cd51019eb9d9c786d6cb178c37f6812d8a41d6914a1edaf0050c051c75d7c358"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.2.10-linux-x64-cflinuxfs3-6649b56e.tgz"
version = "2.2.10"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "a72dc47fb959a0e0e9691e5eb886c08c02850bc7ccdbab21a844e0c3df5fb427"
source = "https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.7.tar.gz"
source_sha256 = "35cd349cddf78e4a0640d28ec8c7e88a2ae0db51ebd8926cd232bb70db2c7d7f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.7-linux-x64-cflinuxfs3-a72dc47f.tgz"
version = "2.3.7"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "34718170ef36d00277ae166d327c0ea4debf4562cd6d79950b1c78cb02cd2c5e"
source = "https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.8.tar.gz"
source_sha256 = "b5016d61440e939045d4e22979e04708ed6c8e1c52e7edb2553cf40b73c59abf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.8-linux-x64-cflinuxfs3-34718170.tgz"
version = "2.3.8"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "3131cb19beeee3701e905bb1738817c5af8be7c150994510e956a1cba98a8ade"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.5-linux-x64-cflinuxfs2-3131cb19.tgz"
version = "2.4.5"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "bedb8b6b620b64b320dbbefe9e7906d277dcaf9e2308c44ecd6deb97e5486964"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.5-linux-x64-cflinuxfs3-bedb8b6b.tgz"
version = "2.4.5"

[[metadata.dependencies]]
id = "ruby"
sha256 = "3f9ed717d4c7e5aa1a871518c051487f78567af7ea71ea6ff3bab1b30078663f"
source = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.6.tar.gz"
source_sha256 = "de0dc8097023716099f7c8a6ffc751511b90de7f5694f401b59f2d071db910be"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.6-linux-x64-cflinuxfs2-3f9ed717.tgz"
version = "2.4.6"

[[metadata.dependencies]]
id = "ruby"
sha256 = "9761fb0d5fe44ba5dce2ea5de77c933a147398a6dc6425ab5aa35eebfa0927f0"
source = "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.6.tar.gz"
source_sha256 = "de0dc8097023716099f7c8a6ffc751511b90de7f5694f401b59f2d071db910be"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.6-linux-x64-cflinuxfs3-9761fb0d.tgz"
version = "2.4.6"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "d275cd81cc8fc2663b3fae42058cf03e1599028f42ff7e3d3291ec4d07b4f1e5"
source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz"
source_sha256 = "dac81822325b79c3ba9532b048c2123357d3310b2b40024202f360251d9829b1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.1-linux-x64-cflinuxfs3-d275cd81.tgz"
version = "2.5.1"

[[metadata.dependencies]]
id = "ruby"
name = "Ruby"
sha256 = "5d5a8f8cdfe44d9136dc7098771b32054c8dd8cd048638c4997e24e19d2675e0"
source = "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.gz"
source_sha256 = "9828d03852c37c20fa333a0264f2490f07338576734d910ee3fd538c9520846c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.3-linux-x64-cflinuxfs3-5d5a8f8c.tgz"
version = "2.5.3"

[[metadata.dependencies]]
id = "ruby"
sha256 = "28d42bddf876152f80bb14f33dc45d008a5700538c339fe3fd73921e15546602"
source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.gz"
source_sha256 = "577fd3795f22b8d91c1d4e6733637b0394d4082db659fccf224c774a2b1c82fb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.3-linux-x64-cflinuxfs2-28d42bdd.tgz"
version = "2.6.3"

[[metadata.dependencies]]
id = "ruby"
sha256 = "5f783afaa368ec9450da8b15aa4b543b186e42d98f2baf6fdb68309b6ce187f2"
source = "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.gz"
source_sha256 = "577fd3795f22b8d91c1d4e6733637b0394d4082db659fccf224c774a2b1c82fb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.6.3-linux-x64-cflinuxfs3-5f783afa.tgz"
version = "2.6.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
