
[buildpack]
id = "org.cloudfoundry.ruby"
name = "Ruby Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.default_versions]]
ruby = "2.4.6"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "6d65b1e27ac44445e951325ab869ed164ad649d04df3129697fde6afe224b66d"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.2.9-linux-x64-6d65b1e2.tgz"
  version = "2.2.9"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "70fe7ff3c4e814160b97ad0812253c4b168416f0abb477419ff93fdbdd104cc7"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.2.10-linux-x64-cflinuxfs2-70fe7ff3.tgz"
  version = "2.2.10"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "6649b56e83ebc5791f6ccff48fa2eec02b112b994fb82297d762364c8cbfb5cc"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.2.10-linux-x64-cflinuxfs3-6649b56e.tgz"
  version = "2.2.10"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "31630396a5f7b712a592728c027ddd7309e617e9d902b7f677fb247869fd8793"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.7-linux-x64-cflinuxfs2-31630396.tgz"
  version = "2.3.7"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "a72dc47fb959a0e0e9691e5eb886c08c02850bc7ccdbab21a844e0c3df5fb427"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.7-linux-x64-cflinuxfs3-a72dc47f.tgz"
  version = "2.3.7"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "7751357a5e72d445ce3739448a9852fa4fc0efacf2fdad9e489744e84f0e5fb0"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.8-linux-x64-cflinuxfs2-7751357a.tgz"
  version = "2.3.8"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "34718170ef36d00277ae166d327c0ea4debf4562cd6d79950b1c78cb02cd2c5e"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.3.8-linux-x64-cflinuxfs3-34718170.tgz"
  version = "2.3.8"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "65674838d8550574481d782ddff83f199021350fc2eb24b4aa0952e6f5375249"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.4-linux-x64-cflinuxfs2-65674838.tgz"
  version = "2.4.4"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "a7d1badf2b68d19d90147b8671bb4aa4247772e1e6fda6764c2c37f1580c9183"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.4-linux-x64-cflinuxfs3-a7d1badf.tgz"
  version = "2.4.4"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "3131cb19beeee3701e905bb1738817c5af8be7c150994510e956a1cba98a8ade"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.5-linux-x64-cflinuxfs2-3131cb19.tgz"
  version = "2.4.5"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "bedb8b6b620b64b320dbbefe9e7906d277dcaf9e2308c44ecd6deb97e5486964"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.4.5-linux-x64-cflinuxfs3-bedb8b6b.tgz"
  version = "2.4.5"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "cf2423b4eb2914ce5e92d3157d519ab909b96d72153be0c8f1558b56b9c78ed8"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.1-linux-x64-cflinuxfs2-cf2423b4.tgz"
  version = "2.5.1"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "d275cd81cc8fc2663b3fae42058cf03e1599028f42ff7e3d3291ec4d07b4f1e5"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.1-linux-x64-cflinuxfs3-d275cd81.tgz"
  version = "2.5.1"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
  id = "ruby"
  sha256 = "b8584ecae59e2ba059bff91f01522c4b012f767a9dfb999883b1e3d8347b3aa3"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.3-linux-x64-cflinuxfs2-b8584eca.tgz"
  version = "2.5.3"

[[metadata.dependencies]]
  name = "Ruby"
  stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
  id = "ruby"
  sha256 = "5d5a8f8cdfe44d9136dc7098771b32054c8dd8cd048638c4997e24e19d2675e0"
  uri = "https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby-2.5.3-linux-x64-cflinuxfs3-5d5a8f8c.tgz"
  version = "2.5.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
